### ISSUE TITLE
Thanks!!!

### ISSUE THREAD

**Issue by bhima6164** [a5a5aa555oo/rtl8188gu#1]
Thanks for making this driver. It works like a charm. 

I am having Tenda W311MI usb adaptor with this driver.

Just now tested on manjaro 22.0.5 with Linux LTS 6.1.19-1 Kernel.

Also tried with endeavour os kernel 6.2.8.

 Working perfectly. Upload speed also good.

One request. Please add dkms support if you can. Thanks.

**Comment by a5a5aa555oo** [comment]
DKMS support added. It should work. :)
